### PR TITLE
get_fig() plotting function

### PR DESCRIPTION
**Pull request by gilbertgong**
# Pull Request
Implement get_fig() per issue 1, generate a Figure object which the user can then browse or write to disk

## Description

Uses the code from the examples to implement get_fig()

Also, a default `pip install -r requirements.txt` resulted in an error, which is fixed by pinning scipy to version 1.8.1

Examples are updated.

## Fixes

pins scipy to avoid potential incompatibility with newer versions

## How Has This Been Tested?

Ran the example files

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
Thanks so much for doing this, do you mind add a screen shot of what the new plots look like? 
Thanks

**Comment by gilbertgong** [comment]
The code is pretty much exactly cut and pasted from the examples so they look pretty much exactly the same as before.

image
image

**Comment by peterdudfield** [comment]
Thanks for this @gilbertgong

**Comment by gilbertgong** [comment]
I'll try consumption next =D

**Comment by peterdudfield** [comment]
#4 could be good to fix too?

**Pull request merged**
